version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aotw-app
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  BeforeInstall:
    - location: scripts/codedeploy/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/codedeploy/post_install.sh
      timeout: 600
      runas: ec2-user
  ApplicationStart:
    - location: scripts/codedeploy/run.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/codedeploy/stop.sh
      timeout: 120
      runas: ec2-user
