version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 3001:3001
    networks:
      - cloud
    depends_on:
      - db
    command: ./scripts/wait-for-it.sh db:5432 -- yarn start:test

  db:
    image: postgres:10.5
    restart: always
    networks:
      - cloud
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: botw
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d botw"]
      interval: 10s
      timeout: 5s
      retries: 5
    
networks:
  cloud:
